name: Internal Packages Tests

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Internal Packages
    runs-on: [self-hosted-linux-amd64-noble-edge]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Ensure No Formatting Changes
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Run Unit and Integration Test of internal packages
        env:
          POSTGRESQL_DB_CONNECT_STRING: postgres://postgres:postgres@localhost:5432/postgres
        run: |
          go test -v -coverprofile=coverage.out -race -tags=integration ./internal/...

      - name: Print coverage report
        run: |
          go tool cover -func=coverage.out

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o=coverage.html

      - uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: coverage.html

      - name: Enforce min coverage (85%)
        run: |
          go tool cover -func=coverage.out | tail -1 | awk '{if ($3 < 85) exit 1}'
          if [ "$?" -ne 0 ]; then
              # use github actions log to print message
              echo "::error::Code coverage is below 85%"
              exit 1
          fi


    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
