name: Publish to edge

on:
  push:
    branches:
      - main
  pull_request:

env:
  CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "true"
  ROCKCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "true"

jobs:
  publish-charm:
    strategy:
      fail-fast: false
      matrix:
        charm:
          - planner
          - webhook-gateway
    name: Publish Charm (${{ matrix.charm }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - name: Remove Android SDK
        run: sudo rm -rf /usr/local/lib/android
      - name: setup lxd
        uses: canonical/setup-lxd@v0.1.3
      - name: rename ${{ matrix.charm }}-rockcraft.yaml
        run: |
          mv ${{ matrix.charm }}-rockcraft.yaml rockcraft.yaml
      - name: build rock
        id: rockcraft
        run: |
          sudo snap install --channel latest/stable --classic rockcraft
          rockcraft pack --verbosity trace
          echo rock=`ls *.rock` >> $GITHUB_OUTPUT
      - run: |
          echo rockcraft pack:
          echo ${{ steps.rockcraft.outputs.rock }}
      - name: upload rock
        run: |
          docker run -d -p 5000:5000 --name registry registry:latest
          rockcraft.skopeo --insecure-policy copy --dest-tls-verify=false oci-archive:${{ steps.rockcraft.outputs.rock }} docker://localhost:5000/rock:latest
      - name: build charm
        id: charmcraft
        working-directory: charms/${{ matrix.charm }}-operator/
        run: |
          sudo snap install --channel latest/stable --classic charmcraft
          charmcraft pack --verbosity trace
          echo charms=`ls -d $PWD/*.charm` >> $GITHUB_OUTPUT
      - run: |
          echo charmcraft pack:
          echo ${{ steps.charmcraft.outputs.charms }}
      - id: charm-name
        working-directory: charms/${{ matrix.charm }}-operator/
        run: |
          echo charm-name=`yq -r .name charmcraft.yaml` >> $GITHUB_OUTPUT
      - run: |
          sudo apt update && sudo apt install python3-yaml -y
      - name: update upstream-source
        working-directory: charms/${{ matrix.charm }}-operator/
        shell: python
        run: |
          import yaml
          
          charmcraft_yaml = yaml.safe_load(open("charmcraft.yaml"))
          resources = charmcraft_yaml["resources"]
          resources[list(resources)[0]]["upstream-source"] = "localhost:5000/rock:latest"
          yaml.dump(charmcraft_yaml, open("charmcraft.yaml", "w"), sort_keys=False)
      - working-directory: charms/${{ matrix.charm }}-operator/
        run: |
          echo upload charm ${{ steps.charm-name.outputs.charm-name }}
      - working-directory: charms/${{ matrix.charm }}-operator/
        run: |
          cat charmcraft.yaml
      - if: github.event_name == 'push'
        name: publish charm
        uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          built-charm-path: ${{ steps.charmcraft.outputs.charms }}
          tag-prefix: ${{ steps.charm-name.outputs.charm-name }}
          charm-path: charms/${{ matrix.charm }}-operator
